stages:   
  - sast
  - build
  - deploy

sast-job:
  stage: sast
  image: 
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [""]
  tags:
  - registry
  only:
    - staging
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
    - "${SONAR_USER_HOME}/cache"
    - sonar-scanner/
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    SONAR_HOST_URL: https://sonarqube.assistx.dev 
  script: 
  - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}"
  allow_failure: true

### BUILD JOB ###

build-job-staging: 
  stage: build
  only:
    - staging
  tags:
    - registry
  environment: staging
  script:
    - docker build -t registry.assistx.dev/assist-tix/backend-api:staging .   
    - docker push registry.assistx.dev/assist-tix/backend-api:staging

build-job-main: 
  stage: build
  only:
    - main
  tags:
    - registry
  environment: production
  script:
    - docker build -t registry.assistx.dev/assist-tix/backend-api:latest .   
    - docker push registry.assistx.dev/assist-tix/backend-api:latest

### DEPLOY JOB ###

deploy-job-staging: 
  stage: deploy
  only:
    - staging
  tags:
    - dev-server-new
  variables:
    GIT_STRATEGY: none
  environment: staging
  script:
    - cd ~/tix
    - docker compose pull api 
    - docker compose up -d 
    - docker image prune -f

deploy-job-main: 
  stage: deploy
  only:
    - main
  tags:
    - prod-assistxticket-k8s
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_CONTEXT_PROD: kecilin-id/kubernetes-agent-config:k8s-assistxticket-prod
  environment: production
  script:
    - kubectl config use-context "$KUBE_CONTEXT_PROD"
    - kubectl apply -f $CI_PROJECT_DIR/kubernetes/prod
    - kubectl rollout restart -f $CI_PROJECT_DIR/kubernetes/prod || true
